import type { Metadata } from "next";
import { Great_Vibes, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-heading',
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-body',
});

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-signature',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const locale = cookieStore.get("NEXT_LOCALE")?.value ?? "en";
  const dir = locale === "ar" ? "rtl" : "ltr";
  
  return (
    <html lang={locale} dir={dir} className={`${montserrat.variable} ${inter.variable} ${greatVibes.variable} bg-animated-gradient`}>
      <body className="antialiased font-sans">{children}</body>
    </html>
  );
}
